# Convenience Makefile for scripts directory
# Just delegates to parent Makefile

.PHONY: help setup bootstrap

help:
	@echo "Run 'make' from parent directory: cd .. && make help"

setup:
	@cd .. && make setup

bootstrap:
	@python3 bootstrap.py
